### ISSUE TITLE
what method for VSE? (csgo alike)

### ISSUE THREAD

**Issue by 99999999999999urmom** [sp00fing/ddos#1]
what method for VSE? (csgo alike)

**Comment by sp00fing** [comment]
Hi. For the csgo server, the TCPBYPASS and five-m method is suitable. It also depends on the hosting provider of the server. These scripts can be used on spoofed vps. Soon I will post a list of hosting where you can buy spoofed servers. Also soon I will add a method exclusively for CSGO servers. 

p.s You can read more about the types of attacks on this site: https://javapipe.com/blog/ddos-types/

**Comment by Reaperv2** [comment]
Hello what is a spoofed vps and how can i get one

**Comment by sp00fing** [comment]
Hi, there is a list of hosting companies providing spoofed vps in my repository

**Comment by iloveyumyumshrimpnoodles** [comment]
> Also soon I will add a method exclusively for CSGO servers.

As CS:GO's engine is the Source Engine, a simple A2S_INFO query flood will suffice (aka VSE).
Note that it does need a challenge system, because the servers will simply drop the queries without a challenge

You can find all the server queries here: https://developer.valvesoftware.com/wiki/Server_queries
